# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: SafeDeploymentFactory
    address:
    - 0xC00aa1E4e30EaB5aF9358beabD9136d5dF0C6540
    abi_file_path: ./abis/SafeDeploymentFactory.json
    handler: ./src/EventHandlers.js
    events:
    - event: SafeDeployed(address indexed safeAddress, address[] owners, uint256 threshold, address indexed creator)

  - name: Safe
    # address: 
    # - 0x5Eb30b75103f9366c8C5821a6E127a100645B10e
    abi_file_path: ./abis/Safe.json
    handler: ./src/EventHandlers.js
    events:
    - event: AddedOwner(address owner, address prevOwner, uint256 threshold)
    - event: ApproveHash(bytes32 msgHash, uint256 payment)
    - event: ChangedThreshold(uint256 threshold)
    - event: DisabledModule(address module)
    - event: EnabledModule(address module)
    - event: ExecutionFailure(bytes32 txHash, uint256 payment)
    - event: ExecutionSuccess(bytes32 txHash, uint256 payment)
    - event: FallbackHandlerChanged(address oldFallbackHandler, address newFallbackHandler)
    - event: RemovedOwner(address owner, address prevOwner, uint256 threshold)
    - event: SafeMultiSigTransaction(address to, uint256 value, bytes data, uint8 operation, uint256 safeTxGas, uint256 baseGas, uint256 gasPrice, address gasToken, address refundReceiver, bytes signatures, bytes additionalInfo)
unordered_multichain_mode: true
preload_handlers: true
